# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: book_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'book_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x62ook_service.proto\"\x19\n\x0b\x42ookRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x11\n\x0f\x42ookListRequest\"M\n\x0c\x42ookResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x13\n\x0buploaded_at\x18\x04 \x01(\t\"/\n\x10\x42ookListResponse\x12\x1b\n\x04\x62ook\x18\x01 \x03(\x0b\x32\r.BookResponse2`\n\x05\x42ooks\x12&\n\x07GetBook\x12\x0c.BookRequest\x1a\r.BookResponse\x12/\n\x08GetBooks\x12\x10.BookListRequest\x1a\x11.BookListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'book_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOKREQUEST']._serialized_start=22
  _globals['_BOOKREQUEST']._serialized_end=47
  _globals['_BOOKLISTREQUEST']._serialized_start=49
  _globals['_BOOKLISTREQUEST']._serialized_end=66
  _globals['_BOOKRESPONSE']._serialized_start=68
  _globals['_BOOKRESPONSE']._serialized_end=145
  _globals['_BOOKLISTRESPONSE']._serialized_start=147
  _globals['_BOOKLISTRESPONSE']._serialized_end=194
  _globals['_BOOKS']._serialized_start=196
  _globals['_BOOKS']._serialized_end=292
# @@protoc_insertion_point(module_scope)
